return {
	require("plugins.colorscheme"),
	require("plugins.whichkey"),
	require("plugins.mason"),
	require("plugins.treesitter"),
	require("plugins.neorg"),
	require("plugins.startuptime"),
	require("plugins.devicons"),
	require("plugins.dressing"),
	require("plugins.treesj"),
	require("plugins.dial"),
	require("plugins.harpoon"),
	require("plugins.neotree"),
	require("plugins.lsp"),
}
